### ISSUE TITLE
Using route() instead of url()

### ISSUE THREAD

**Issue by cdarken** [sohelamin/crud-generator#264]
Hi. Thanks for this very useful package.
I believe that using the route() helper instead of url() would simplify a lot the templates.
In principle I could use the route names instead the prefix, but because you append a / to the routeGroup option I have to modify the templates manually after I generate them.
If you don't have time for this modification I could make a pull request when I can.

**Comment by tiagofrancafernandes** [comment]
I agree with the suggestion of the @cdarken

**Comment by sohelamin** [comment]
@cdarken @tiagofrancafernandes Added route() helper instead of url()
Also updated the package please use and give your valuable feedback.
Thanks
